export const marks = [
  {
    value: 1,
    label: '1',
  },
  {
    value: 5,
    label: '5',
  },
  {
    value: 10,
    label: '10',
  },
  {
    value: 20,
    label: '20',
  },
  {
    value: 30,
    label: '30',
  },
  {
    value: 40,
    label: '40',
  },
  {
    value: 50,
    label: '50',
  },
];

export const gContentList = [
    'All features in free subscription',
    'Grain heading',
    'Recommendations generated by the Croptomize statistical frame',
    'Full access to suite of Croptomize Intelligence tools: pricing frames for all available grain contracts, ' +
    'historical data, premium market commentary, data analytics, and more precise hedging tools',
    'Dynamically estimate farm profitability based on live market prices',
]

export const gMenuText = [
    'Home',
    'Product',
    'About',
    'Pricing',
    'Blog',
    'Contact'
]
